apiVersion: v1
kind: Service
metadata:
  namespace: test-workflow
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
